import argparse
import os
from pathlib import Path

CURRENT_PATH = Path(__file__).resolve().parent
REPO_ROOT = CURRENT_PATH.parent.parent
SRC_PATH = REPO_ROOT / "src"
MEMORY_FILE = REPO_ROOT / "memory.mem"

PROJECT_NAME = "0dMIPS"
PART = "xc7a100tfgg484-2"
TOP = "SOC"
VERILOG_DEFINES = ["LED_ENABLED"]

# These modules are guarded by defines or are Verilator-only.  Keeping them out
# makes the generated project smaller than Vivado's write_project_tcl output.
OMITTED_SYNTH_SOURCES = {
    SRC_PATH / "units" / "VGA.sv",
    SRC_PATH / "units" / "stdout.sv",
    SRC_PATH / "modules" / "xpm_memory_sdpram_verilator.sv",
}

TARGET_CONSTRS = [CURRENT_PATH / "DaVinci_Pro_PIN.xdc"]
DEBUG_CONSTRS = [CURRENT_PATH / "Debug.xdc"]
# Implementation-only constraints (floorplan / pblocks): applied in impl, not synth.
IMPL_CONSTRS = [CURRENT_PATH / "Floorplan.xdc"]


def collect_sources():
    return sorted(
        path
        for suffix in ("*.sv", "*.v")
        for path in SRC_PATH.rglob(suffix)
        if path not in OMITTED_SYNTH_SOURCES
    )


def collect_ip_files():
    return sorted(CURRENT_PATH.glob("*.xci"))


def resolve_output_path(target_path):
    target_path = target_path.expanduser()
    if target_path.suffix == ".tcl":
        return target_path
    return target_path / "create_proj.tcl"


def rel_to_script(path, script_dir):
    return os.path.relpath(path.resolve(), script_dir.resolve()).replace(os.sep, "/")


def tcl_source_path(path, script_dir):
    return f'[file normalize "$script_dir/{rel_to_script(path, script_dir)}"]'


def tcl_list(paths, script_dir):
    if not paths:
        return "[list]"
    lines = ["[list \\"]
    for path in paths:
        lines.append(f"  {tcl_source_path(path, script_dir)} \\")
    lines[-1] = lines[-1].rstrip(" \\")
    lines.append("]")
    return "\n".join(lines)


def emit_tcl(output_path):
    script_dir = output_path.resolve().parent
    sources = collect_sources()
    ip_files = collect_ip_files()
    memory_file = MEMORY_FILE if MEMORY_FILE.exists() else None
    defines = " ".join(VERILOG_DEFINES)

    lines = [
        "# Minimal Vivado project generated by generate_vivado_project.py",
        "# Source paths are relative to this Tcl file location.",
        "# Usage: vivado -mode tcl -source create_proj.tcl",
        "",
        "set script_dir [file dirname [file normalize [info script]]]",
        f'set project_name "{PROJECT_NAME}"',
        f'set part_name "{PART}"',
        'set project_dir [file normalize "$script_dir"]',
        "",
        "create_project -force $project_name $project_dir -part $part_name",
        'set_property default_lib "xil_defaultlib" [current_project]',
        'set_property mem.enable_memory_map_generation "1" [current_project]',
        "",
        f"set source_files {tcl_list(sources, script_dir)}",
        "add_files -norecurse -fileset [get_filesets sources_1] $source_files",
        'set_property file_type "SystemVerilog" [get_files -of_objects [get_filesets sources_1] $source_files]',
        f'set_property top "{TOP}" [get_filesets sources_1]',
        f"set_property verilog_define {{{defines}}} [get_filesets sources_1]",
        "",
        f"set ip_files {tcl_list(ip_files, script_dir)}",
        "if {[llength $ip_files] > 0} {",
        "  import_files -norecurse -fileset [get_filesets sources_1] $ip_files",
        "  set imported_ip_files [get_files -of_objects [get_filesets sources_1] *.xci]",
        "  generate_target all $imported_ip_files",
        "}",
        "",
        f"set constr_files {tcl_list(TARGET_CONSTRS + DEBUG_CONSTRS + IMPL_CONSTRS, script_dir)}",
        "add_files -norecurse -fileset [get_filesets constrs_1] $constr_files",
        'set_property file_type "XDC" [get_files -of_objects [get_filesets constrs_1] $constr_files]',
    ]

    for constrs in TARGET_CONSTRS:
        lines.extend(
            [
                f"set target_xdc {tcl_source_path(constrs, script_dir)}",
                "set_property target_constrs_file $target_xdc [get_filesets constrs_1]",
                "set_property target_part $part_name [get_filesets constrs_1]",
            ]
        )

    for constrs in DEBUG_CONSTRS:
        lines.extend(
            [
                f"set debug_xdc {tcl_source_path(constrs, script_dir)}",
                'set_property used_in "implementation" [get_files -of_objects [get_filesets constrs_1] $debug_xdc]',
                "set_property used_in_synthesis false [get_files -of_objects [get_filesets constrs_1] $debug_xdc]",
            ]
        )

    for constrs in IMPL_CONSTRS:
        lines.extend(
            [
                f"set impl_xdc {tcl_source_path(constrs, script_dir)}",
                'set_property used_in "implementation" [get_files -of_objects [get_filesets constrs_1] $impl_xdc]',
                "set_property used_in_synthesis false [get_files -of_objects [get_filesets constrs_1] $impl_xdc]",
            ]
        )

    if memory_file is not None:
        lines.extend(
            [
                "",
                f"set memory_file {tcl_source_path(memory_file, script_dir)}",
                "add_files -norecurse -fileset [get_filesets sources_1] $memory_file",
                'set_property file_type "Memory File" [get_files -of_objects [get_filesets sources_1] $memory_file]',
            ]
        )

    lines.extend(
        [
            "",
            "update_compile_order -fileset sources_1",
            "update_compile_order -fileset sim_1",
            "",
            'if {[string equal [get_runs -quiet synth_1] ""]} {',
            '  create_run -name synth_1 -part $part_name -flow "Vivado Synthesis 2025" -strategy "Vivado Synthesis Defaults" -constrset constrs_1',
            "}",
            'if {[string equal [get_runs -quiet impl_1] ""]} {',
            '  create_run -name impl_1 -parent_run synth_1 -part $part_name -flow "Vivado Implementation 2025" -strategy "Vivado Implementation Defaults" -constrset constrs_1',
            "}",
            "current_run -synthesis [get_runs synth_1]",
            "current_run -implementation [get_runs impl_1]",
            "",
        ]
    )

    return "\n".join(lines)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate a minimal Vivado project Tcl for this board."
    )
    parser.add_argument(
        "target_path",
        type=Path,
        default=CURRENT_PATH / "create_proj.tcl",
        help="Output .tcl path, or a directory where create_proj.tcl should be written.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    output_path = resolve_output_path(args.target_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(emit_tcl(output_path), encoding="utf-8")
    print(f"Generated Vivado project Tcl at {output_path.absolute()}")
    print("Usage: vivado -mode tcl -source create_proj.tcl")


if __name__ == "__main__":
    main()
